server:
  port: 9999
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://192.168.0.44:8888
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://192.168.0.44:8888
          predicates:
            - Path=/inventory-service/**
